sudo: false
dist: trusty
language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-pictures
      - texlive-science
      - pgf
      #
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - lmodern

install:
  - pip install pyyaml matplotlib numpy scipy
cache: pip

env:
  - secure: "H7qnDjxiYeCDv7nVW8QyOnhzw44AmVYPRChyHxpD7yH3DqVDjzkstDLBpD9t97qtMIPLeULss22rFz/q2tmEI5+8G8uHQCd1jBzoT7Qb5shZaUQAQawx8HUp3Krj9OpCBQENH/Uyo5N6UkZg0JcLLtkc+ZwgBCEkjokcksx7hvRPSYmHnm1ILTsThNvAZkMre2bGi7Uirpmyj77GndbaZHmXq77XS06g7JW8gRHEjp/tLlyGCSRz4cxk3v55PmCsoccLJSfRvAY/S3dGJtiux3BTU4U0lNNhZ+iEg7V/Ffr3Z/naXY/zV4OpNFLN07MU/33RscZRWnaZS5LZnADZ56ECIzNx+tnj+0NkvOvSpRA8iTcEaSGOuTJND9jO58n5u0HMmbwFdhw5eXbOvkvBxQUQ/5vDfUTnZKtl4OKgPs9ZjeJeKhuKG0vmo+wP8uxL/LLDSSPDByDDwZvtpqguOUlMy81uJ+bAheZoV97LpL6xJSZ8QXFD61AE/tZo+aNtyXLTzaPcc6m7RUcTO0tCjiXWMLAacoW8kjVgcv7lSxzu7bPRUD2jg7AIenOxG0G8VFBdw1aGuBXoFUS+kAfAizP1aoI6UpAhElpzrHsHhY87kRO3qNgPgcB9KZG+7rRMpKWPKxJJj2qKr2Mu7pNMNNbiy4ftsjvHBehkbPLt6Ig="

before_script:
  # We need to setup a display for matplotlib plotting
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3  # Some time to start xvfb

script:
  - cd "${TRAVIS_BUILD_DIR}"
  #
  # Setup build and build overlay
  - ${TRAVIS_BUILD_DIR}/ci/checkout_overlay.sh
  - mkdir ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
  - cmake ..
  - . ../dissertation-build-overlay/setup.sh
  #
  # Build the document
  - cmake --build .

deploy:
  provider: releases
  api_key:
    secure: "rBlFy5om9pa8gsGR2hnvAta7l7V22QV2so3PaE/huFweHx9lvKhhRkaJ3wW/yffPQQ9hMCN8fs9zkb+c8EhQqT2Zf2FYo8/BNOQ3VxootKqR+rPaApU+YTIfyPiOCblGSK5adelW28ZgtJtlD2hFnvZRbbekqlgjUskup7ACn86vzD/VifgMAYC402Qjtoyy34viOhsygAxzK5AGupt70iZZyvCxKJTDMJHXhmA//ZcgNKkb7/lwwOCP0qJPu6mtUsOnt7ZGMIZqpvbxYBLGpa/0hK4e2ZNRMDriQN+SU/IbWIpkWWNV7HQw1YHRHtSDYKKWtrwT57sEm3ll7h8qa0D9pQxXGsE9WxLGTkn1uJL+4Jty+lbB6xE9SW4fxg2wtXZrxu16qyzE+eT5aRtH5iI6i+NVviJ7EqEEFVKwjZ1xSi3X7uwj/xDzupocXuunGkrdMAd5N9h2GA06qGkuvr7p8L7ecDRMkulKsX8oaxI3NVBizfGzz6rFnuX0vmDR18ZlZlWBJb5gmxOFSzBfNgKFP562Co26YDXyczt+fGXdJLRnmrFITObTo0ss0rdcKLqi7k597TkzJ1V1xcDblwn75wbN1bGe4/rTYpNn3NpGDQon+3W+3PnH+oVGZ8aP8xayDjBF6WJd/kMtshl0SfSHoZvAwheOu08lYsQQa6o="
  file: ${TRAVIS_BUILD_DIR}/build/dissertation.pdf
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: mfherbst/dissertation
