#!/usr/bin/env python3

from matplotlib import pyplot as plt
import common
import os
import scipy.io
import yaml


def main():
    common.setup()

    # This file was generated by the program h_poisson_schrödinger
    # using roughly the following settings:
    #   - Be atom
    #   - Grid: Finer inner grid [-20, 20] bohr in each direction (x, y, z)
    #   - Outer grid: coarser, range [-200, 200] bohr in each direction
    #   - Inner grid twice refined
    #   - hcore guess
    #   - Around 10 SCF steps with adaptive refinement
    #   - quadratic finite elements
    #
    fefile = "./Be.fe.stiff.mtx.gz"
    if not os.path.isfile(fefile):
        raise SystemExit("Cannot plot fe.pdf, since fe data file not found.")

    fe = scipy.io.mmread(fefile).todense()
    props = common.mtx_properties(fe)
    common.plot_mtcs([fe])
    plt.savefig("fock_fe.pdf", bbox_inches="tight", dpi=300)

    with open("fock_fe_props.yaml", "w") as f:
        yaml.safe_dump(props, f)


if __name__ == "__main__":
    main()
